[package]
name = "rcl-validator"
version.workspace = true
edition.workspace = true
description = "RCL Validator"
[dependencies]
rcl-types = { workspace = true }
rcl-meaning = { workspace = true }
rcl-intent = { workspace = true }
rcl-commitment = { workspace = true }
thiserror = { workspace = true }
