[package]
name = "maple-mwl-identity"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Compatibility wrapper for worldline-identity"

[dependencies]
worldline-identity = { workspace = true }
