[package]
name = "rcl-audit"
version.workspace = true
edition.workspace = true
description = "RCL Audit"
[dependencies]
rcl-types = { workspace = true }
rcl-meaning = { workspace = true }
rcl-intent = { workspace = true }
rcl-commitment = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
