[package]
name = "maple-integration"
version.workspace = true
edition.workspace = true
description = "maple integration"

[dependencies]
rcf-types = { workspace = true }
rcf-meaning = { workspace = true }
rcf-intent = { workspace = true }
rcf-commitment = { workspace = true }
rcf-validator = { workspace = true }
mrp-types = { workspace = true }
aas-types = { workspace = true }
