[package]
name = "rcf-compiler"
version.workspace = true
edition.workspace = true
description = "RCF Compiler"
[dependencies]
rcf-types = { workspace = true }
rcf-commitment = { workspace = true }
rcf-validator = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
