[package]
name = "maple-mwl-types"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Compatibility wrapper for worldline-types"

[dependencies]
worldline-types = { workspace = true }
