[package]
name = "resonator-profiles"
version.workspace = true
edition.workspace = true
description = "resonator profiles"

[dependencies]
thiserror = { workspace = true }
rcf-types = { workspace = true }
rcf-meaning = { workspace = true }
rcf-intent = { workspace = true }
rcf-commitment = { workspace = true }
mrp-types = { workspace = true }
aas-types = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
